// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'roundData.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RoundData _$RoundDataFromJson(Map<String, dynamic> json) => RoundData(
      id: json['id'] as int?,
      venue_name: json['venue_name'] as String?,
      round_name: json['round_name'] as String?,
      round_type: json['round_type'] as String?,
      gender: json['gender'] as String?,
      is_score: json['is_score'] as String?,
      sport_name: json['sport_name'] as String?,
      timestamp: json['timestamp'] as String?,
      score1: json['score1'],
      score2: json['score2'],
      team1_college_name: json['team1_college_name'] as String?,
      team2_college_name: json['team2_college_name'] as String?,
      team3_college_name: json['team3_college_name'] as String?,
      team4_college_name: json['team4_college_name'] as String?,
      team5_college_name: json['team5_college_name'] as String?,
      team6_college_name: json['team6_college_name'] as String?,
      team7_college_name: json['team7_college_name'] as String?,
      team8_college_name: json['team8_college_name'] as String?,
      part1: json['part1'] as String?,
      part2: json['part2'] as String?,
      part3: json['part3'] as String?,
      part4: json['part4'] as String?,
      part5: json['part5'] as String?,
      part6: json['part6'] as String?,
      part7: json['part7'] as String?,
      part8: json['part8'] as String?,
      winner1: json['winner1'] as String?,
      sport_id: json['sport_id'] as int?,
      winner2: json['winner2'] as String?,
      winner3: json['winner3'] as String?,
    );

Map<String, dynamic> _$RoundDataToJson(RoundData instance) => <String, dynamic>{
      'id': instance.id,
      'venue_name': instance.venue_name,
      'round_name': instance.round_name,
      'round_type': instance.round_type,
      'gender': instance.gender,
      'is_score': instance.is_score,
      'sport_name': instance.sport_name,
      'sport_id': instance.sport_id,
      'timestamp': instance.timestamp,
      'score1': instance.score1,
      'score2': instance.score2,
      'team1_college_name': instance.team1_college_name,
      'team2_college_name': instance.team2_college_name,
      'team3_college_name': instance.team3_college_name,
      'team4_college_name': instance.team4_college_name,
      'team5_college_name': instance.team5_college_name,
      'team6_college_name': instance.team6_college_name,
      'team7_college_name': instance.team7_college_name,
      'team8_college_name': instance.team8_college_name,
      'part1': instance.part1,
      'part2': instance.part2,
      'part3': instance.part3,
      'part4': instance.part4,
      'part5': instance.part5,
      'part6': instance.part6,
      'part7': instance.part7,
      'part8': instance.part8,
      'winner1': instance.winner1,
      'winner2': instance.winner2,
      'winner3': instance.winner3,
    };
